</main>
<footer class="site">
  Generated by Classic ASP on IIS &middot;
  Server time <%= HtmlEncode(Now()) %> &middot;
  VBScript engine v<%= ScriptEngineMajorVersion() & "." & ScriptEngineMinorVersion() %> &middot;
  <a href="index.asp">&laquo; All samples</a>
</footer>
</body>
</html>
