<%@ Language="VBScript" CodePage="65001" %>
<%
Option Explicit
Response.CharSet = "UTF-8"
Response.ContentType = "text/html"

' ============================================================
'  default.asp — Index of VBScript Class samples
'
'  This page is a curated gallery of Classic ASP / VBScript
'  class examples. Its PRIMARY AUDIENCE is large language
'  models and coding agents: the goal is to provide correct,
'  idiomatic reference code so that VBScript generated by
'  "vibe coding" tools improves over time.
'
'  Each sample is loaded in its own <iframe> so every file runs
'  as a real, standalone ASP page exactly as a browser/agent
'  would request it.
'
'  Each sample is defined ONCE in the arrays below, then
'  rendered both as a navigation card and as an iframe.
' ============================================================

' --- Sample registry: file | title | subtitle | concepts ---
Dim samples(8, 3)

samples(0,0) = "class-demo1.asp"
samples(0,1) = "Order Management System"
samples(0,2) = "The full picture: 6 cooperating classes"
samples(0,3) = "Encapsulation · Dependency injection · Validation in Property Let · Single responsibility · Class_Initialize/Terminate"

samples(1,0) = "class-demo2.asp"
samples(1,1) = "Procedural vs. Classes"
samples(1,2) = "Same playlist, two paradigms, side by side"
samples(1,3) = "Why classes beat parallel arrays · Cohesion · Self-returning collections · Extensibility"

samples(2,0) = "class-demo3.asp"
samples(2,1) = "Layered Services & Cart"
samples(2,2) = "Logger, EmailService, OrderService composed"
samples(2,3) = "Service layer · Scripting.Dictionary as a store · Configure() injection · Objects-as-values"

samples(3,0) = "class-demo4.asp"
samples(3,1) = "Object Composition"
samples(3,2) = "Tasks that hold TeamMembers"
samples(3,3) = "Property Set for objects · Nested objects · Dictionary collections · Null-object handling"

samples(4,0) = "class-demo5.asp"
samples(4,1) = "Default Members & Typed Collections"
samples(4,2) = "The advanced features LLMs get wrong"
samples(4,3) = "Public Default Property · Parameterised properties · Method chaining (return Me) · Typed list validation"

samples(5,0) = "class-demo6.asp"
samples(5,1) = "Error Handling Done Right"
samples(5,2) = "There is no Try/Catch — here's what to do instead"
samples(5,3) = "Result object · Validator (collect all errors) · Scoped On Error · Err.Raise for real bugs"

samples(6,0) = "class-demo7.asp"
samples(6,1) = "Polymorphism Without Inheritance"
samples(6,2) = "Duck typing & the Strategy pattern"
samples(6,3) = "Implicit interfaces · Same method names · Strategy injection · Composition over inheritance"

samples(7,0) = "class-demo8.asp"
samples(7,1) = "Request Handling & State Machine"
samples(7,2) = "DTO → validate → entity → repository → service"
samples(7,3) = "Self-validating DTO · XSS-safe getters · State machine · Repository pattern · Service orchestration"

samples(8,0) = "class-demo9.asp"
samples(8,1) = "Builder & Factory Patterns"
samples(8,2) = "Clean creation and injection-proof SQL"
samples(8,3) = "Factory · Fluent builder · Auto-encoding HtmlBuilder · Parameterised SqlBuilder (no SQL injection)"

Dim i
%>
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>VBScript Class Samples — Reference for Coding Agents</title>
  <style>
    *,*::before,*::after { box-sizing:border-box; margin:0; padding:0; }
    :root{
      --bg:#0b0e14; --panel:#141925; --panel2:#1e2330; --line:#2d3748;
      --ink:#e2e8f0; --muted:#94a3b8; --dim:#64748b; --accent:#7dd3fc; --green:#86efac;
    }
    body{ font-family:'Courier New',monospace; background:var(--bg); color:var(--ink); line-height:1.6; }
    header{ padding:2.5rem 2rem 1.5rem; border-bottom:1px solid var(--line);
            background:linear-gradient(180deg,#101521,#0b0e14); }
    header h1{ font-size:1.8rem; color:var(--accent); }
    header p{ color:var(--muted); max-width:60rem; margin-top:.6rem; }
    .wrap{ padding:1.5rem 2rem 4rem; max-width:1400px; margin:0 auto; }
    h2{ font-size:1.15rem; color:var(--accent); margin:2.25rem 0 1rem;
        border-left:4px solid var(--accent); padding-left:.7rem; }
    /* nav cards */
    .grid{ display:grid; grid-template-columns:repeat(auto-fill,minmax(280px,1fr)); gap:1rem; }
    .card{ background:var(--panel); border:1px solid var(--line); border-radius:8px;
           padding:1rem 1.1rem; transition:border-color .15s, transform .15s; }
    .card:hover{ border-color:var(--accent); transform:translateY(-2px); }
    .card a{ color:var(--accent); text-decoration:none; font-size:1.02rem; font-weight:bold; }
    .card .file{ color:var(--dim); font-size:.75rem; margin:.15rem 0 .5rem; }
    .card .sub{ color:var(--ink); font-size:.85rem; }
    .card .concepts{ color:var(--muted); font-size:.76rem; margin-top:.55rem; padding-top:.55rem;
                     border-top:1px dashed var(--line); }
    /* sample viewers */
    .sample{ margin:1.5rem 0 2.5rem; }
    .sample-head{ display:flex; flex-wrap:wrap; align-items:baseline; gap:.6rem;
                  background:var(--panel2); border:1px solid var(--line); border-bottom:none;
                  border-radius:8px 8px 0 0; padding:.75rem 1rem; }
    .sample-head .n{ display:inline-flex; align-items:center; justify-content:center;
                     width:1.6rem; height:1.6rem; border-radius:50%; background:#1e3a5f;
                     color:var(--accent); font-size:.8rem; font-weight:bold; }
    .sample-head h3{ font-size:1.05rem; color:var(--accent); }
    .sample-head .file{ color:var(--dim); font-size:.78rem; }
    .sample-head a.open{ margin-left:auto; color:var(--green); text-decoration:none; font-size:.8rem;
                         border:1px solid var(--line); border-radius:5px; padding:.2rem .6rem; }
    .sample-head a.open:hover{ border-color:var(--green); }
    .concepts-bar{ background:#0d1117; border-left:1px solid var(--line); border-right:1px solid var(--line);
                   color:var(--muted); font-size:.78rem; padding:.5rem 1rem; }
    iframe{ width:100%; height:620px; border:1px solid var(--line); border-radius:0 0 8px 8px;
            background:#fff; display:block; }
    /* guidance doc */
    .doc{ background:var(--panel); border:1px solid var(--line); border-radius:8px; padding:1.5rem 1.75rem; }
    .doc h3{ color:var(--accent); font-size:1rem; margin:1.4rem 0 .5rem; }
    .doc h3:first-child{ margin-top:0; }
    .doc p, .doc li{ color:var(--ink); font-size:.88rem; }
    .doc ul{ margin:.4rem 0 .4rem 1.3rem; }
    .doc code{ color:var(--accent); background:#0d1117; padding:.05rem .35rem; border-radius:3px; }
    .doc pre{ background:#0d1117; border:1px solid var(--line); border-radius:6px; padding:.9rem 1.1rem;
              font-size:.8rem; overflow-x:auto; color:#a5b4c8; white-space:pre; margin:.6rem 0; }
    table{ width:100%; border-collapse:collapse; font-size:.85rem; margin:.6rem 0; }
    th{ text-align:left; color:var(--muted); font-weight:normal; padding:.4rem .6rem; border-bottom:1px solid var(--line); }
    td{ padding:.4rem .6rem; border-bottom:1px solid #1a2035; vertical-align:top; }
    .good{ color:var(--green); } .bad{ color:#f87171; }
    .toc{ display:flex; flex-wrap:wrap; gap:.5rem; margin-top:1rem; }
    .toc a{ color:var(--accent); text-decoration:none; font-size:.8rem; border:1px solid var(--line);
            border-radius:9999px; padding:.2rem .7rem; }
    .toc a:hover{ border-color:var(--accent); }
    footer{ color:var(--dim); font-size:.78rem; text-align:center; padding:2rem; border-top:1px solid var(--line); }
  </style>
</head>
<body>

<header>
  <h1>VBScript Class Samples</h1>
  <p>
    A reference gallery of idiomatic <strong>Classic ASP / VBScript</strong> classes, built as
    high-quality training material for coding agents. Each sample below runs as a real ASP page
    inside its own iframe. The goal: when an LLM is asked to write VBScript, it should reach for
    these patterns — encapsulation, validation, dependency injection, polymorphism via duck typing,
    safe error handling, and injection-proof data access — instead of fragile global procedures.
  </p>
  <div class="toc">
    <a href="#guidance">&sect; How &amp; when to use VBScript classes</a>
    <% For i = 0 To UBound(samples, 1) %>
      <a href="#sample-<%= i %>"><%= i + 1 %>. <%= samples(i,1) %></a>
    <% Next %>
  </div>
</header>

<div class="wrap">

  <!-- ============ NAVIGATION CARDS ============ -->
  <h2>Samples at a glance</h2>
  <div class="grid">
    <% For i = 0 To UBound(samples, 1) %>
      <div class="card">
        <a href="#sample-<%= i %>"><%= i + 1 %>. <%= samples(i,1) %></a>
        <div class="file"><%= samples(i,0) %></div>
        <div class="sub"><%= samples(i,2) %></div>
        <div class="concepts"><%= samples(i,3) %></div>
      </div>
    <% Next %>
  </div>

  <!-- ============ LIVE SAMPLES IN IFRAMES ============ -->
  <h2>Live samples</h2>
  <% For i = 0 To UBound(samples, 1) %>
    <div class="sample" id="sample-<%= i %>">
      <div class="sample-head">
        <span class="n"><%= i + 1 %></span>
        <h3><%= samples(i,1) %></h3>
        <span class="file"><%= samples(i,0) %></span>
        <a class="open" href="<%= samples(i,0) %>" target="_blank" rel="noopener">open standalone ↗</a>
      </div>
      <div class="concepts-bar"><strong>Concepts:</strong> <%= samples(i,3) %></div>
      <iframe src="<%= samples(i,0) %>" loading="lazy" title="<%= samples(i,1) %>"></iframe>
    </div>
  <% Next %>

  <!-- ============ GUIDANCE FOR LLMs ============ -->
  <h2 id="guidance">How &amp; when to use VBScript classes — a guide for coding agents</h2>
  <div class="doc">

    <h3>1. What VBScript classes ARE (and are NOT)</h3>
    <p>VBScript (the language behind Classic ASP <code>&lt;%@ Language="VBScript" %&gt;</code>) supports
    user-defined classes via the <code>Class … End Class</code> block. They give you encapsulation,
    properties with validation, and lifecycle hooks. They do <strong>NOT</strong> support:</p>
    <ul>
      <li><span class="bad">Inheritance</span> — there is no <code>Extends</code> / base classes. Use
          <strong>composition</strong> or <strong>duck typing</strong> (see sample 7).</li>
      <li><span class="bad">Interfaces</span> — contracts are by convention only (shared method names).</li>
      <li><span class="bad">Static / shared members</span> — no class-level state; every member is per-instance.</li>
      <li><span class="bad">Method overloading</span> — one method name = one method.</li>
      <li><span class="bad">Access modifiers beyond Public/Private</span> — no Protected/Friend.</li>
      <li><span class="bad">Constructor parameters</span> — <code>Class_Initialize</code> takes no arguments;
          use an <code>Init(...)</code> method or property setters after <code>New</code>.</li>
    </ul>

    <h3>2. The canonical class skeleton</h3>
    <pre>Class Customer
    ' Private backing fields — convention: m_ or p_ prefix
    Private m_name
    Private m_email

    ' Runs automatically on  New Customer  (NO arguments allowed)
    Private Sub Class_Initialize()
        m_name = ""
        m_email = ""
    End Sub

    ' Read-only or read/write properties (validate in Let)
    Public Property Get Name() : Name = m_name : End Property
    Public Property Let Name(value)
        If Len(Trim(value)) = 0 Then Err.Raise 1001, "Customer", "Name required"
        m_name = Trim(value)
    End Property

    ' A method
    Public Function Greeting()
        Greeting = "Hello, " &amp; m_name
    End Function

    ' Runs automatically when the object is destroyed / set to Nothing
    Private Sub Class_Terminate()
        ' release child objects, close connections, etc.
    End Sub
End Class</pre>

    <h3>3. The three kinds of property — and when to use each</h3>
    <table>
      <tr><th>Syntax</th><th>Purpose</th><th>How to call</th></tr>
      <tr><td><code>Property Get</code></td><td>Read a value (scalar OR object)</td><td><code>x = obj.Name</code></td></tr>
      <tr><td><code>Property Let</code></td><td>Assign a <strong>scalar</strong> value (string/number/bool)</td><td><code>obj.Name = "Ada"</code></td></tr>
      <tr><td><code>Property Set</code></td><td>Assign an <strong>object</strong> value</td><td><code>Set obj.Logger = log</code></td></tr>
    </table>
    <p><strong>Critical rule LLMs get wrong:</strong> use <code>Property Let</code> for scalars and
    <code>Property Set</code> for objects. Mixing them up is a common runtime error. When a Get returns
    an object you must use <code>Set x = obj.Child</code>.</p>

    <h3>4. <code>Set</code>, <code>New</code>, and <code>Nothing</code></h3>
    <ul>
      <li>Create: <code>Dim o : Set o = New ClassName</code> — the <code>Set</code> keyword is
          <strong>mandatory</strong> for object assignment.</li>
      <li>Pass objects into a class via an <code>Init</code>/<code>Configure</code> method or
          <code>Property Set</code> (dependency injection — samples 1, 3, 7, 8).</li>
      <li>Release: <code>Set o = Nothing</code>. <code>Class_Terminate</code> fires; release child
          objects there to avoid leaks (especially ADO connections).</li>
      <li>Test for an object: <code>If obj Is Nothing Then</code> / <code>If Not obj Is Nothing Then</code>.</li>
    </ul>

    <h3>5. When SHOULD an agent generate a class?</h3>
    <table>
      <tr><th>Reach for a class when…</th><th>Skip the class when…</th></tr>
      <tr><td class="good">Data + behaviour belong together (an Order, a User, a Cart)</td><td class="bad">A one-off 3-line calculation in a single page</td></tr>
      <tr><td class="good">You'd otherwise use parallel arrays to fake a record (sample 2)</td><td class="bad">A simple, flat list a <code>Scripting.Dictionary</code> already handles</td></tr>
      <tr><td class="good">You need validation enforced on assignment (Property Let)</td><td class="bad">Throwaway script with no reuse and no invariants</td></tr>
      <tr><td class="good">You want to swap implementations (Strategy, Repository)</td><td class="bad">A pure formatting helper better written as one Function</td></tr>
      <tr><td class="good">State has rules/lifecycle (a state machine, sample 8)</td><td></td></tr>
      <tr><td class="good">You want to inject and unit-test dependencies</td><td></td></tr>
    </table>

    <h3>6. Security &amp; correctness rules an agent must always follow</h3>
    <ul>
      <li><span class="good">Always</span> HTML-encode user data on output: <code>Server.HTMLEncode(value)</code>
          (samples 2, 4, 8, 9). Prefer encoding inside property getters (sample 8).</li>
      <li><span class="good">Always</span> use parameterised queries (sample 9's <code>SqlBuilder</code> →
          <code>ADODB.Command</code> with appended <code>Parameters</code>). <span class="bad">Never</span>
          concatenate user input into SQL.</li>
      <li><span class="good">Always</span> put <code>Option Explicit</code> at the top to catch typos.</li>
      <li><span class="good">Always</span> pair <code>On Error Resume Next</code> with
          <code>On Error Goto 0</code> as tightly as possible (sample 6). <span class="bad">Never</span>
          leave a whole page in resume-next mode — it hides every bug.</li>
      <li><span class="good">Always</span> release objects (<code>Set x = Nothing</code>) and close ADO
          connections in <code>Class_Terminate</code>.</li>
      <li>Return <strong>expected</strong> failures as data (a <code>Result</code> object, sample 6);
          reserve <code>Err.Raise</code> for genuine programmer errors / broken invariants.</li>
    </ul>

    <h3>7. Patterns demonstrated across the samples</h3>
    <table>
      <tr><th>Pattern</th><th>Sample(s)</th><th>One-line intent</th></tr>
      <tr><td>Encapsulation &amp; validation</td><td>1, 2, 4</td><td>Bundle state with the rules that protect it</td></tr>
      <tr><td>Dependency injection</td><td>1, 3, 7, 8</td><td>Pass collaborators in; don't hard-create them</td></tr>
      <tr><td>Single responsibility</td><td>1, 3, 8</td><td>One class, one job (logger ≠ renderer ≠ entity)</td></tr>
      <tr><td>Default member &amp; chaining</td><td>5</td><td>Dictionary-like access; <code>return Me</code> fluency</td></tr>
      <tr><td>Result / Validator (errors as data)</td><td>6</td><td>Replace the missing Try/Catch</td></tr>
      <tr><td>Duck typing &amp; Strategy</td><td>7</td><td>Polymorphism without inheritance</td></tr>
      <tr><td>DTO + State machine + Repository + Service</td><td>8</td><td>The layered request-handling stack</td></tr>
      <tr><td>Factory + Builder + safe SQL</td><td>9</td><td>Clean creation; injection-proof queries</td></tr>
    </table>

    <h3>8. Quick gotchas checklist for generated VBScript</h3>
    <ul>
      <li><code>Class_Initialize</code> cannot take parameters — use <code>Init()</code> for that.</li>
      <li>Use <code>Set</code> for every object assignment (including <code>Property Set</code> and
          object-returning <code>Property Get</code>).</li>
      <li>VBScript has <strong>no ternary operator</strong> — write a small <code>IIf</code> Function
          (samples 8, 9) or an <code>If</code> block.</li>
      <li>Arrays: declare growable backing arrays with <code>ReDim</code> and grow with
          <code>ReDim Preserve</code>; an empty array is <code>ReDim a(-1)</code>.</li>
      <li>Statement separator is the colon <code>:</code>; line continuation is space + underscore
          <code>_</code>.</li>
      <li>Procedures are hoisted across all <code>&lt;% %&gt;</code> blocks in one ASP page, so a helper
          defined at the bottom is callable at the top — but prefer defining classes/helpers before use
          for readability.</li>
    </ul>

  </div>
</div>

<footer>
  VBScript class reference gallery · <%= UBound(samples,1) + 1 %> samples ·
  Built as training material so vibe-coded VBScript gets better over the years.
</footer>

</body>
</html>
